import { Region } from './region';
import { User } from './user';
import { Direction } from './direction';
import { PostType } from './post-type';
import { PostImage } from './post-image';
import { Category } from './category';
import {Comment} from './comment';
export interface Post {
  id: number;
  title: string;
  condition: boolean;
  address: string;
  region: Region;
  area: number;
  price: number;
  deal: boolean;
  viewCount: number;
  content: string;
  status: boolean;
  approved: boolean;
  user: User;
  category: Category;
  postImages: PostImage[];
  postType: PostType;
  direction: Direction;
  comments: Comment[];
  createdAt: Date;
  updatedAt: Date;
  customerType: boolean;
}
